const MODIFICAR_APELLIDO = "MODIFICAR_APELLIDO";
const AUMENTAR_CONTADOR = "AUMENTAR_CONTADOR";
const MODIFICAR_AMIGOS = "MODIFICAR_AMIGOS";
const CAMBIAR_NOMBRE = "CAMBIAR_NOMBRE";

module.exports = {
    AUMENTAR_CONTADOR,
    CAMBIAR_NOMBRE,
    MODIFICAR_AMIGOS,
    MODIFICAR_APELLIDO  
}
